### ISSUE TITLE
Allow use to configure the IS path and Tomcat Path once and try out the samples

### ISSUE THREAD

**Issue by mefarazath** [wso2/samples-is#71]
Sometimes its annoying when users have to copy paste the tomcat and IS path during the run of each sample.

I would suggest to either read it from an environment variable. If the environment variable is not set then we can prompt for the path in the QSG scripts.

**Comment by GDRDABARERA** [comment]
Fixed with https://github.com/wso2/samples-is/pull/79/commits/2f1dc183dcea66495edc7a45c6b013aae6c1b3e8

Added a server.properties file inside bin folder to configure paths of WSO2 IS and tomcat servers
